Repository selsa-inube/inubekit-assisted, pull requests merged in 2024-04, with the labels that each got.

#3 Add size prop
  package.json
  src/Assisted/index.tsx
  src/Assisted/props.ts
  src/Assisted/stories/Assisted.stories.tsx
  src/Assisted/styles.js
  vite.config.ts
Labels: major

#10 remove unnecessary code
  .github/workflows/auto-release.yml
Labels: patch

#11 remove unnecessary code
  .github/workflows/auto-release.yml
Labels: patch

#12 fix: update dependencies in order to change the place foundations
  .github/workflows/auto-release.yml
  package.json
Labels: minor

#6 Refactor `<Assisted />` component to use new token structure
  CHANGELOG.md
  package.json
  src/Assisted/index.tsx
  src/Assisted/stories/Assisted.stories.tsx
  src/Assisted/styles.js
  src/index.ts
Labels: major

#5 Adjust and export interfaces
  CHANGELOG.md
  src/Assisted/index.tsx
  src/Assisted/props.ts
  src/index.ts
Labels: major

#13 fix(assisted): refactor component so it uses theme from ThemeContext
  package.json
  src/Assisted/index.tsx
Labels: minor

#14 Explore how we can use status checks to prevent merges with failed builds
  .github/workflows/auto-release.yml
Labels: minor
