Repository selsa-inube/inubekit-assisted, pull requests merged in 2024-09, with the labels that each got.

#41 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#42 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#43 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#44 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#45 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#47 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#48 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#46 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#49 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#50 Fcanas/adjust assisted responsive
  src/Assisted/ProgressBar/index.tsx
  src/Assisted/ProgressBar/styles.js
  src/Assisted/StepIndicator/index.tsx
  src/Assisted/StepIndicator/styles.js
  src/Assisted/index.tsx
  src/Assisted/interface.tsx
  src/Assisted/props.ts
  src/Assisted/stories/Assisted.Controller.tsx
  src/Assisted/stories/Assisted.stories.tsx
  src/Assisted/styles.js
  src/index.ts
Labels: major

#51 feat: extend interface to control disabled back, next and submit buttons
  src/Assisted/index.tsx
  src/Assisted/interface.tsx
  src/Assisted/stories/Assisted.Controller.tsx
  src/Assisted/stories/Assisted.stories.tsx
Labels: major

#52 chore: update button dependency to 4.39.1
  package.json
Labels: patch

#53 feat: extend interface to get step id
  src/Assisted/interface.tsx
  src/Assisted/props.ts
  src/Assisted/stories/Assisted.Controller.tsx
  src/Assisted/stories/Assisted.stories.tsx
Labels: major

#54 Move assisted tokens from foundations to component
  src/Assisted/ProgressBar/styles.js
  src/Assisted/StepIndicator/index.tsx
  src/Assisted/StepIndicator/styles.js
  src/Assisted/Tokens/tokens.ts
  src/Assisted/index.tsx
  src/Assisted/interface.tsx
  src/Assisted/stories/Assisted.stories.tsx
  src/Assisted/styles.js
Labels: minor

#55 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#56 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#57 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#58 Update text dependency to latest version
  package.json
Labels: minor, dependencies
